package io.jacob.episodive.core.network.model

import com.google.gson.annotations.SerializedName

data class EpisodeResponse(
    @SerializedName("id") val id: Long,
    @SerializedName("guid") val guid: String,
    @SerializedName("title") val title: String,
    @SerializedName("link") val link: String,
    @SerializedName("description") val description: String,
    @SerializedName("datePublished") val datePublished: Long,
    @SerializedName("dateCrawled") val dateCrawled: Long,
    @SerializedName("enclosureUrl") val enclosureUrl: String,
    @SerializedName("enclosureType") val enclosureType: String,
    @SerializedName("enclosureLength") val enclosureLength: Int,
    @SerializedName("startTime") val startTime: Long,
    @SerializedName("endTime") val endTime: Long,
    @SerializedName("status") val status: String,
    @SerializedName("contentLink") val contentLink: String? = null,
    @SerializedName("duration") val duration: Int? = null,
    @SerializedName("explicit") val explicit: Int,
    @SerializedName("episode") val episode: Int? = null,
    @SerializedName("episodeType") val episodeType: String? = null,
    @SerializedName("season") val season: Int? = null,
    @SerializedName("image") val image: String,
    @SerializedName("podcastGuid") val podcastGuid: String? = null,
    @SerializedName("feedItunesId") val feedItunesId: Long? = null,
    @SerializedName("feedImage") val feedImage: String,
    @SerializedName("feedId") val feedId: Long,
    @SerializedName("feedUrl") val feedUrl: String? = null,
    @SerializedName("feedAuthor") val feedAuthor: String? = null,
    @SerializedName("feedTitle") val feedTitle: String? = null,
    @SerializedName("feedLanguage") val feedLanguage: String,
    @SerializedName("feedDuplicateOf") val feedDuplicateOf: Long? = null,
    @SerializedName("chaptersUrl") val chaptersUrl: String? = null,
    @SerializedName("transcriptUrl") val transcriptUrl: String? = null,
    @SerializedName("transcripts") val transcripts: List<TranscriptResponse>? = null,
    @SerializedName("soundbites") val soundbites: List<SoundbiteResponse>? = null,
    @SerializedName("persons") val persons: List<PersonResponse>? = null,
    @SerializedName("categories") val categories: Map<Int, String>? = null,
)

/*
{
    "id": 42340708554,
    "title": "인도네시아에 나부끼는 밀집모자 해적단 깃발",
    "link": "https://podcasters.spotify.com/pod/show/qus1gd6ab6g/episodes/ep-e37s17n",
    "description": "<p>1. 반정부 시위에 등장한 '원피스 해적 깃발'</p><p>2. 인도네시아 군부 역사</p><p>3. 인도네시아 군부는 '천룡인'인가</p>",
    "guid": "cc3f0d77-7a98-4c28-9240-514c4574eb9f",
    "datePublished": 1757451600,
    "datePublishedPretty": "September 09, 2025 4:00pm",
    "dateCrawled": 1757502528,
    "enclosureUrl": "https://anchor.fm/s/ddaceaa8/podcast/play/107922103/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2025-8-6%2F407003366-44100-2-ee66b7943e5d.mp3",
    "enclosureType": "audio/mpeg",
    "enclosureLength": 16723799,
    "duration": 1045,
    "explicit": 0,
    "episode": null,
    "episodeType": "full",
    "season": 0,
    "image": "https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/37090970/37090970-1679992813357-7ebb5a0de140c.jpg",
    "feedItunesId": 1639494417,
    "feedImage": "https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/37090970/37090970-1679992813357-7ebb5a0de140c.jpg",
    "feedId": 5778530,
    "podcastGuid": "7eddd03e-20ae-5a29-ae59-a1a9c8091322",
    "feedTitle": "슈카월드",
    "feedLanguage": "ko",
    "chaptersUrl": null
}
 */