package io.jacob.episodive.core.network.model

import com.google.gson.annotations.SerializedName

data class EpisodeResponse(
    @SerializedName("id") val id: Long,
    @SerializedName("title") val title: String,
    @SerializedName("link") val link: String,
    @SerializedName("description") val description: String? = null,
    @SerializedName("guid") val guid: String,
    @SerializedName("datePublished") val datePublished: Long,
    @SerializedName("dateCrawled") val dateCrawled: Long,
    @SerializedName("enclosureUrl") val enclosureUrl: String,
    @SerializedName("enclosureType") val enclosureType: String,
    @SerializedName("enclosureLength") val enclosureLength: Long,
    @SerializedName("startTime") val startTime: Long? = null,
    @SerializedName("endTime") val endTime: Long? = null,
    @SerializedName("status") val status: String? = null,
    @SerializedName("contentLink") val contentLink: String? = null,
    @SerializedName("duration") val duration: Int? = null,
    @SerializedName("explicit") val explicit: Int,
    @SerializedName("episode") val episode: Int? = null,
    @SerializedName("episodeType") val episodeType: String? = null,
    @SerializedName("season") val season: Int? = null,
    @SerializedName("image") val image: String,
    @SerializedName("feedItunesId") val feedItunesId: Long? = null,
    @SerializedName("feedImage") val feedImage: String,
    @SerializedName("feedId") val feedId: Long,
    @SerializedName("feedUrl") val feedUrl: String? = null,
    @SerializedName("feedAuthor") val feedAuthor: String? = null,
    @SerializedName("feedTitle") val feedTitle: String? = null,
    @SerializedName("feedLanguage") val feedLanguage: String,
    @SerializedName("categories") val categories: Map<Int, String>? = null,
    @SerializedName("chaptersUrl") val chaptersUrl: String? = null,
    @SerializedName("transcriptUrl") val transcriptUrl: String? = null,
    @SerializedName("transcripts") val transcripts: List<TranscriptResponse>? = null,
)
