package io.jacob.episodive.core.network.model

import com.google.gson.annotations.SerializedName

data class PodcastResponse(
    @SerializedName("id") val id: Long,
    @SerializedName("podcastGuid") val podcastGuid: String,
    @SerializedName("title") val title: String,
    @SerializedName("url") val url: String,
    @SerializedName("originalUrl") val originalUrl: String,
    @SerializedName("link") val link: String,
    @SerializedName("description") val description: String,
    @SerializedName("author") val author: String,
    @SerializedName("ownerName") val ownerName: String,
    @SerializedName("image") val image: String,
    @SerializedName("artwork") val artwork: String,
    @SerializedName("lastUpdateTime") val lastUpdateTime: Long,
    @SerializedName("lastCrawlTime") val lastCrawlTime: Long,
    @SerializedName("lastParseTime") val lastParseTime: Long,
    @SerializedName("lastGoodHttpStatusTime") val lastGoodHttpStatusTime: Long,
    @SerializedName("lastHttpStatus") val lastHttpStatus: Int,
    @SerializedName("contentType") val contentType: String,
    @SerializedName("itunesId") val itunesId: Long? = null,
    @SerializedName("itunesType") val itunesType: String? = null,
    @SerializedName("generator") val generator: String? = null,
    @SerializedName("language") val language: String,
    @SerializedName("explicit") val explicit: Boolean? = null,
    @SerializedName("type") val type: Int,
    @SerializedName("medium") val medium: String? = null,
    @SerializedName("dead") val dead: Int,
    @SerializedName("chash") val chash: String? = null,
    @SerializedName("episodeCount") val episodeCount: Int,
    @SerializedName("crawlErrors") val crawlErrors: Int,
    @SerializedName("parseErrors") val parseErrors: Int,
    @SerializedName("categories") val categories: Map<Int, String>? = null,
    @SerializedName("locked") val locked: Int,
    @SerializedName("imageUrlHash") val imageUrlHash: Long? = null,
//    @SerializedName("value") val value: Value4Value? = null,
//    @SerializedName("funding") val funding: Funding? = null,
    @SerializedName(value = "newestItemPubdate", alternate = ["newestItemPublishTime"]) val newestItemPublishTime: Long? = null,
)
