package io.jacob.episodive.core.network.model

import com.google.gson.annotations.SerializedName

data class PodcastResponse(
    @SerializedName("id") val id: Long,
    @SerializedName("podcastGuid") val podcastGuid: String,
    @SerializedName("title") val title: String,
    @SerializedName("url") val url: String,
    @SerializedName("originalUrl") val originalUrl: String,
    @SerializedName("link") val link: String,
    @SerializedName("description") val description: String,
    @SerializedName("author") val author: String,
    @SerializedName("ownerName") val ownerName: String,
    @SerializedName("image") val image: String,
    @SerializedName("artwork") val artwork: String,
    @SerializedName("lastUpdateTime") val lastUpdateTime: Long,
    @SerializedName("lastCrawlTime") val lastCrawlTime: Long,
    @SerializedName("lastParseTime") val lastParseTime: Long,
    @SerializedName("lastGoodHttpStatusTime") val lastGoodHttpStatusTime: Long,
    @SerializedName("lastHttpStatus") val lastHttpStatus: Int,
    @SerializedName("contentType") val contentType: String,
    @SerializedName("itunesId") val itunesId: Long? = null,
    @SerializedName("itunesType") val itunesType: String? = null,
    @SerializedName("generator") val generator: String? = null,
    @SerializedName("language") val language: String,
    @SerializedName("explicit") val explicit: Boolean? = null,
    @SerializedName("type") val type: Int,
    @SerializedName("medium") val medium: String? = null,
    @SerializedName("dead") val dead: Int,
    @SerializedName("chash") val chash: String? = null,
    @SerializedName("episodeCount") val episodeCount: Int,
    @SerializedName("crawlErrors") val crawlErrors: Int,
    @SerializedName("parseErrors") val parseErrors: Int,
    @SerializedName("categories") val categories: Map<Int, String>? = null,
    @SerializedName("locked") val locked: Int,
    @SerializedName("imageUrlHash") val imageUrlHash: Long? = null,
//    @SerializedName("value") val value: Value4Value? = null,
//    @SerializedName("funding") val funding: Funding? = null,
    @SerializedName(value = "newestItemPubdate", alternate = ["newestItemPublishTime"]) val newestItemPublishTime: Long? = null,
)

/*
{
    "id": 5778530,
    "title": "슈카월드",
    "url": "https://anchor.fm/s/ddaceaa8/podcast/rss",
    "originalUrl": "http://pod.ssenhosting.com/rss/pb_33508/pbchannel_48285.xml",
    "link": "https://podcasters.spotify.com/pod/show/qus1gd6ab6g",
    "description": "어렵고 딱딱한 경제,시사,금융 이야기를\n쉽고 유쾌하게 풀어내는 \n경제/시사/이슈/잡썰 토크방송입니다.\n매일 오전 6시 슈카월드\n광고/ 제휴 문의 : syukaworld2@naver.com",
    "author": "슈카친구들",
    "ownerName": "슈카친구들",
    "image": "https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/37090970/37090970-1679992813357-7ebb5a0de140c.jpg",
    "artwork": "https://d3t3ozftmdmh3i.cloudfront.net/production/podcast_uploaded_nologo/37090970/37090970-1679992813357-7ebb5a0de140c.jpg",
    "lastUpdateTime": 1757568578,
    "lastCrawlTime": 1757568555,
    "lastParseTime": 1757568579,
    "inPollingQueue": 0,
    "priority": -1,
    "lastGoodHttpStatusTime": 1757568555,
    "lastHttpStatus": 200,
    "contentType": "",
    "itunesId": 1639494417,
    "generator": "Anchor Podcasts",
    "language": "ko",
    "type": 0,
    "dead": 0,
    "crawlErrors": 0,
    "parseErrors": 0,
    "categories": {
        "9": "Business"
    },
    "locked": 0,
    "explicit": false,
    "podcastGuid": "7eddd03e-20ae-5a29-ae59-a1a9c8091322",
    "medium": "podcast",
    "episodeCount": 610,
    "imageUrlHash": 1979648873,
    "newestItemPubdate": 1757451600
}
 */